export const genres = [
    'Art',
    'Biography',
    'Business',
    'Classics',
    'Comics',
    'Cookbooks',
    'Crime',
    'Ebooks',
    'Fantasy',
    'Fiction',
    'History',
    'Horror',
    'Comedy',
    'Memoir',
    'Music',
    'Mystery',
    'Nonfiction',
    'Philosophy',
    'Poetry',
    'Psychology',
    'Romance',
    'Science',
    'Science Fiction',
    'Sports',
    'Thriller',
    'Travel'
]